apiVersion: template.openshift.io/v1
kind: Template
labels:
  app: loki
  template: loki-template
metadata:
  name: loki
  namespace: openshift
objects:

- apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: loki
    namespace: ${GRAFANA_PROJECT_NAME}
    labels:
      app: loki
      group: grafana

- apiVersion: v1
  kind: ConfigMap
  metadata:
    name: loki-config
    namespace: ${GRAFANA_PROJECT_NAME}
  data:
    loki-config.yaml: |-
  
      auth_enabled: false
    
      server:
        http_listen_port: 3100
      
      ingester:
        lifecycler:
          address: 127.0.0.1
          ring:
            kvstore:
              store: inmemory
            replication_factor: 1
          final_sleep: 0s
        # chunk_idle_period: 1m
        # chunk_retain_period: 30s
        flush_op_timeout: 20s
        # max_transfer_retries: 1

        max_transfer_retries: 10
        chunk_retain_period: 15s
        chunk_idle_period: 30s
        chunk_block_size: 131072
      
      schema_config:
        configs:
          - from: 2018-04-15
            store: boltdb
            object_store: aws
            schema: v11
            index:
              prefix: loki_index
              period: 360h
            chunks:
              prefix: chunk
              period: 360h
      
      storage_config:
        boltdb:
           directory: /loki/index
        aws:
          # s3: http://${AZURE_SA_NAME}:${AZURE_SA_KEY}@minio.default.svc:9000/loki-chunks
          # s3: s3://${AZURE_SA_NAME}:${AZURE_SA_KEY}@minio-default.20.50.45.2.nip.io/loki-chunks
          s3: s3://${AZURE_SA_NAME}:${AZURE_SA_KEY}@minio.default.svc:9000/loki-chunks
          s3forcepathstyle: true

- apiVersion: "v1"
  kind: "PersistentVolumeClaim"
  metadata:
    name: loki-storage
    namespace: ${GRAFANA_PROJECT_NAME}
  spec:
    accessModes:
      - ${STORAGE_ACCSESS_MODE}
    resources:
      requests:
        storage: ${STORAGE_SIZE}        

- apiVersion: apps/v1beta2
  kind: Deployment
  metadata:
    name: loki
    namespace: ${GRAFANA_PROJECT_NAME}
    labels:
      app: loki
      group: grafana
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: loki
        group: grafana
    template:
      metadata:
        labels:
          app: loki
          group: grafana
      spec:
        serviceAccountName: loki
        containers:
          - name: loki
            # image: grafana/loki:1.5.0
            # image: grafana/loki:1.4.1
            image: grafana/loki:master
            imagePullPolicy: IfNotPresent
            args: ['-config.file=/etc/loki/loki-config.yaml']
            resources:
              limits:
                cpu: '1'
                memory: 2Gi
              requests:
                cpu: '1'
                memory: 1Gi
            ports:
              - containerPort: 3100
                protocol: TCP
            volumeMounts:
            - name: loki-config
              mountPath: /etc/loki/
            - name: loki-data
              mountPath: /loki
        volumes:
          - name: loki-config
            configMap:
              name: loki-config
          - name: loki-data
            persistentVolumeClaim:
              claimName: loki-storage
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        serviceAccountName: loki
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
        


- apiVersion: v1
  kind: Service
  metadata:
    name: loki
    namespace: ${GRAFANA_PROJECT_NAME}
    labels:
      app: loki
      group: grafana
  spec:
    type: ClusterIP
    ports:
      - name: 3100-tcp
        port: 3100
        protocol: TCP
        targetPort: 3100
    selector:
      app: loki
      group: grafana
    sessionAffinity: None
      

#Variables
parameters:
- description: Project (Namespace)
  displayName: Project (Namespace)
  name: GRAFANA_PROJECT_NAME
  # value: "loki-grafana"

- description: Storage type
  displayName: Starage
  name: STORAGE_ACCSESS_MODE
  value: "ReadWriteOnce"

- description: Storage size.
  displayName: Storage size
  name: STORAGE_SIZE
  value: "10Gi"

- description: Azure Storage Account Name.
  displayName: Azure Storage Account Name
  name: AZURE_SA_NAME
  value: "XXXXXXXXXXXXXX"

- description: Azure Storage Account Key.
  displayName: Azure Storage Account Key
  name: AZURE_SA_KEY
  value: "XXXXXXXXXXXXXX"
