apiVersion: template.openshift.io/v1
kind: Template
labels:
  app: loki
  template: loki-template
metadata:
  name: loki
  namespace: openshift
objects:

- apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: loki
    namespace: ${GRAFANA_PROJECT_NAME}
    labels:
      app: loki
      group: grafana

- apiVersion: v1
  kind: ConfigMap
  metadata:
    name: loki-config
    namespace: ${GRAFANA_PROJECT_NAME}
  data:
    loki-config.yaml: |-
  
      auth_enabled: false

      server:
        http_listen_port: 3100
      
      ingester:
        lifecycler:
          address: 127.0.0.1
          ring:
            kvstore:
              store: inmemory
            replication_factor: 1
          final_sleep: 0s
        chunk_idle_period: 5m
        chunk_retain_period: 30s
        max_transfer_retries: 0
      
      schema_config:
        configs:
          - from: 2018-04-15
            store: boltdb
            object_store: filesystem
            schema: v11
            index:
              prefix: index_
              period: 168h
      
      storage_config:
        boltdb:
          directory: /loki/index
      
        filesystem:
          directory: /loki/chunks
      
      limits_config:
        enforce_metric_name: false
        reject_old_samples: true
        reject_old_samples_max_age: 168h
      
      chunk_store_config:
        max_look_back_period: 0s
      
      table_manager:
        retention_deletes_enabled: false
        retention_period: 0s
 
- apiVersion: "v1"
  kind: "PersistentVolumeClaim"
  metadata:
    name: loki-storage
    namespace: ${GRAFANA_PROJECT_NAME}
  spec:
    accessModes:
      - ${STORAGE_ACCSESS_MODE}
    resources:
      requests:
        storage: ${STORAGE_SIZE}

- apiVersion: apps/v1
  kind: StatefulSet
  metadata:
    name: loki
    namespace: ${GRAFANA_PROJECT_NAME}
    labels:
      app: loki
      group: grafana
  spec:
    podManagementPolicy: OrderedReady
    replicas: 1
    selector:
      matchLabels:
        app: loki
        group: grafana
    serviceName: loki-headless
    updateStrategy:
      type: RollingUpdate
    template:
      metadata:
        labels:
          app: loki
          group: grafana
      spec:
        containers:
          - name: loki
            # image: grafana/loki:latest
            image: grafana/loki:1.5.0
            imagePullPolicy: IfNotPresent
            args: ['-config.file=/etc/loki/loki-config.yaml']
            ports:
              - name: http-metrics
                containerPort: 3100
                protocol: TCP
            livenessProbe:
              httpGet:
                path: /ready
                port: http-metrics
              initialDelaySeconds: 45
            readinessProbe:
              httpGet:
                path: /ready
                port: http-metrics
              initialDelaySeconds: 45

            volumeMounts:
            - name: loki-config
              mountPath: /etc/loki/
            - name: loki-data
              mountPath: /loki
        volumes:
          - name: loki-config
            configMap:
              name: loki-config
          # - name: storage
          #   emptyDir: {}
          - name: loki-data
            persistentVolumeClaim:
              claimName: loki-storage
        serviceAccountName: loki
        securityContext:
          # fsGroup: 10001
          # runAsGroup: 10001
          runAsNonRoot: true
          # runAsUser: 10001
        initContainers:
          []
        terminationGracePeriodSeconds: 4800

- apiVersion: v1
  kind: Service
  metadata:
    name: loki
    namespace: ${GRAFANA_PROJECT_NAME}
    labels:
      app: loki
      group: grafana
  spec:
    type: NodePort
    ports:
      - port: 3100
        targetPort: 3100
        protocol: TCP
    selector:
      app: loki
      group: grafana


#Variables
parameters:
- description: Project (Namespace)
  displayName: Project (Namespace)
  name: GRAFANA_PROJECT_NAME
  # value: "loki-grafana"

- description: Storage type
  displayName: Starage
  name: STORAGE_ACCSESS_MODE
  value: "ReadWriteOnce"

- description: Storage size.
  displayName: Storage size
  name: STORAGE_SIZE
  value: "20Gi"