apiVersion: template.openshift.io/v1
kind: Template
labels:
  app: mikio
  template: minio-template
metadata:
  name: minio
  namespace: openshift
parameters:
  - description: Project (Namespace)
    displayName: Project (Namespace)
    name: NAMESPACE
    value: "default"
  
  - description: Storage type
    displayName: Starage
    name: STORAGE_ACCSESS_MODE
    value: "ReadWriteOnce"
  
  - description: Storage size.
    displayName: Storage size
    name: STORAGE_SIZE
    value: "20Gi"

  - description: Azure Storage Account Name.
    displayName: Azure Storage Account Name
    name: AZURE_SA_NAME
    value: "XXXXXXXXXXXXXXXX"
  
  - description: Azure Storage Account Key.
    displayName: Azure Storage Account Key
    name: AZURE_SA_KEY
    value: "XXXXXXXXXXXXXXXX"

objects:

- apiVersion: v1
  kind: Secret
  type: Opaque
  metadata:
    annotations: {}
    name: azure-storage-account-access
    namespace: ${NAMESPACE}
  stringData:
    azure_storage-account-name: ${AZURE_SA_NAME}
    azure_storage-account-key: ${AZURE_SA_KEY}

- apiVersion: v1
  kind: Service
  metadata:
    name: minio
    labels:
      app: minio
    namespace: ${NAMESPACE}
  spec:
    type: ClusterIP
    ports:
      - name: 9000-tcp
        port: 9000
        protocol: TCP
        targetPort: 9000
    selector:
      app: minio
    sessionAffinity: None

- apiVersion: apps.openshift.io/v1
  kind: DeploymentConfig
  metadata:
    name: minio
    namespace: ${NAMESPACE}
    labels:
      app: minio
  spec:
    replicas: 1
    selector:
      app: minio
      deploymentconfig: minio
    strategy:
      activeDeadlineSeconds: 21600
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: minio
          deploymentconfig: minio
      spec:
        automountServiceAccountToken: false
        containers:
          - args:
              - gateway
              - azure
              - '--compat'
            env:
              - name: MINIO_ACCESS_KEY
                valueFrom:
                  secretKeyRef:
                    name: azure-storage-account-access
                    key: azure_storage-account-name
              - name: MINIO_SECRET_KEY
                valueFrom:
                  secretKeyRef:
                    name: azure-storage-account-access
                    key: azure_storage-account-key
              # - name: MINIO_BROWSER
              #   value: 'off'
              - name: MINIO_PROMETHEUS_AUTH_TYPE
                value: public
              # - name: MINIO_API_REQUESTS_MAX
              #   value: '3200'
              # - name: MINIO_API_REQUESTS_DEADLINE
              #   value: '4m'
            # image: 'minio/minio:RELEASE.2020-03-14T02-21-58Z'
            image:  minio/minio:latest
            imagePullPolicy: IfNotPresent
            name: minio
            ports:
              - containerPort: 9000
                protocol: TCP
            resources: {}
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        # nodeSelector:
        #   region: infra
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
    test: false
    triggers:
      - type: ConfigChange